//! The binary embeds `assets/` via `include_dir`, whose macro expansion
//! cargo cannot track on its own. Without this, an asset regenerated by
//! the tools would not land in the next build until something else touched
//! the source file holding the macro.
fn main() {
    println!("cargo:rerun-if-changed=assets");
}
